#!/bin/bash
set -e;

if [ -n "${POSTGRES_NON_ROOT_USER:-}" ] && [ -n "${POSTGRES_NON_ROOT_PASSWORD:-}" ]; then
	psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
		CREATE USER ${POSTGRES_NON_ROOT_USER} WITH PASSWORD '${POSTGRES_NON_ROOT_PASSWORD}';
		GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_NON_ROOT_USER};

		GRANT CREATE ON SCHEMA public TO ${POSTGRES_NON_ROOT_USER};
		CREATE SCHEMA IF NOT EXISTS notifications AUTHORIZATION ${POSTGRES_USER};

		GRANT USAGE ON SCHEMA notifications TO ${POSTGRES_NON_ROOT_USER};
		GRANT CREATE ON SCHEMA notifications TO ${POSTGRES_NON_ROOT_USER};

		ALTER DEFAULT PRIVILEGES IN SCHEMA notifications
		GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${POSTGRES_NON_ROOT_USER};
	EOSQL
else
	echo "SETUP INFO: No Environment variables given!"
fi
